[package]
edition = "2021"
name = "bambi-browser"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "client/",
    "server/"
]

[[bin]]
name = "client"
path = "client/src/main.rs"