[package]
edition = "2021"
name = "server"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }
bluer = { version = "0.15.7", features = ["full"] }
env_logger = "0.10"
futures = "0.3.28"
rand = "0.8"